version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5342:80"
      - "5341:5341"
    volumes:
      - /path/to/seq-data:/data
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  addition:
    build:
      context: .
      dockerfile: Addition-API/Dockerfile
    ports:
      - "8081:8080"
      - "8082:8081"
    depends_on:
      - seq

  subtraction:
    build:
      context: .
      dockerfile: Subtraction/SubtractionAPI/Dockerfile
    ports:
      - "8083:8080"
      - "8084:8081"
    depends_on:
      - seq

  multiplication:
    build:
      context: .
      dockerfile: MultiplicationAPI/Dockerfile
    ports:
      - "8085:8080"
      - "8086:8081"
    depends_on:
      - seq

  division:
    build:
      context: .
      dockerfile: Division-API/Dockerfile
    ports:
      - "8087:8080"
      - "8088:8081"
    depends_on:
      - seq

  memory:
    build:
      context: .
      dockerfile: MemoryAPI/Dockerfile
    ports:
      - "8089:8080"
      - "80890:8081"
    depends_on:
      - seq

  calculatorgateway:
    build:
      context: .
      dockerfile: Calculator/CalculatorAPI/Dockerfile
    ports:
      - "8091:8080"
      - "8092:8081"
    depends_on:
      - seq
      - addition
      - subtraction
      - multiplication
      - division
      - memory

